Update README.md
chaoss/wg-diversity-inclusion pull request #357
Opened 2021-03-30 17:55 UTC by germonprez

Signed-off-by: Matt Germonprez <germonprez@gmail.com>

This is a pretty substantial change to the README and I would appreciate discussion on the proposed changes. I thought I'd start with DEI regarding a template for other WGs to build from regarding their own READMEs. 

One thing that I wonder is the naming of people. This can get pretty hard to manage (maintainers, core, contributors). 

Feedback welcome!

2021-03-31 22:46 UTC, jwflory requested changes
I left feedback and suggestions in review. Most of this looks good as-is; my most significant change was noting our Working Group's goal of defining metrics and methods that measure and center DEI in FOSS. 😀 

Also appreciate the helpful notes, like meeting day/time and agenda!

2021-03-31 22:46 UTC, jwflory commented on README.md
> +The DEI working group meets every Wednesday at 10:00am US Central / 3:00pm UTC / 5:00 pm Central Europe Time via [Zoom](https://zoom.us/j/4998687533)
I recommend writing whichever time is absolute and always true (there is always _one_ time zone that has the preferential time). Daylight Savings is tricky, and Europe might abolish it in 2022, so let's write one time and then use a time-converter site for people to click a link and see what time it converts to their local location.

Does this make sense?

2021-03-31 22:46 UTC, jwflory commented on README.md
> +Diversity, equity, and inclusion are central to the health of open source communities. The CHAOSS Diversity, Equity, & Inclusion (DEI) Working Group aims at bringing experiences to help others center
We define metrics to help measure DEI, let's put that up front too. Also capitalizing "Open Source" as it is a proper noun and it is good to be explicit about what we mean when we say "open source."

```suggestion
Diversity, equity, and inclusion are central to the health of open source communities. The CHAOSS Diversity, Equity, & Inclusion (DEI) Working Group aims to define metrics and methods to help others measure and center diversity, equity, and inclusion in their own Open Source projects. The CHAOSS DEI Working Group establishes and broadly communicates an ethical, peer-validated, research-informed, set of standards and best practices for measuring diversity, equity, and inclusion in Open Source projects. We invite anyone interested in the topic of diversity, equity, and inclusion to learn more, and join us. See [Contributing](#contributing) below to become part of our community.
```

2021-03-31 22:46 UTC, jwflory commented on README.md
>  |[Recognition of Good Work](./focus-areas/recognition/) | Identify how we recognize/reward good work in our community.|
Are these still relevant? It might be good to revisit these as a Working Group again. This is the first time I remember these coming up in my year participating with the DEI WG.

2021-03-31 22:46 UTC, jwflory commented on README.md
>  - [Kevin Lumbard](https://github.com/klumb)
Maybe we should check that the names we list here are indeed up-to-date. Or, maybe we should remove this and consider what are more effective ways to note attribution (new metrics release notes?). Open to thoughts. 🙂 

```suggestion
- [Kevin Lumbard](https://github.com/klumb)
- [Justin W. Flory](https://jwf.io)
```

2021-04-05 10:24 UTC, germonprez commented on README.md
> +The DEI working group meets every Wednesday at 10:00am US Central / 3:00pm UTC / 5:00 pm Central Europe Time via [Zoom](https://zoom.us/j/4998687533)
It does make sense. I've also just spent about 30 minutes per daylight saving changes and updated things that way too. Do you a have a preferred timezone converter? If so, I'll just do that and set all things to UTC.

2021-04-05 10:26 UTC, germonprez commented on README.md
>  - [Kevin Lumbard](https://github.com/klumb)
I think we should start leaving names off the README. It's pretty problematic across all WGs.

2021-04-05 10:26 UTC, merged