Create Time Inclusion Metric
chaoss/wg-diversity-inclusion pull request #368
Opened 2021-07-19 03:10 UTC by trajaram23

2021-07-19 18:43 UTC, Nebrethar requested changes
Great work! I left a couple of suggestions, overall nice job.

The DCO (failed check) is complicated, so I'll leave it up to @klumb on whether they want to set it to "pass" for this PR.

2021-07-19 18:43 UTC, Nebrethar commented on focus-areas/time-inclusion.md
> +
Suggestion: Remove optional headers

2021-07-19 18:43 UTC, Nebrethar commented on focus-areas/time-inclusion.md
> +Examples of Global Inclusion which can be implemented include:
This one was my bad.

Suggestion: Change "Global Inclusion" to "Time Inclusion"

2021-07-21 15:06 UTC, Nebrethar approved these changes

2021-07-21 15:11 UTC, sgoggins commented on focus-areas/time-inclusion.md
> +Examples of Global Inclusion which can be implemented include:
Please add this text below the metric title: 

### This metric is a release candidate. To comment on this metric please see Issue [#[put the respective Issue Number here]](URL to issue). Following a comment period, this metric will be included in the next regular release.

Also, please open an corresponding issue, and link that specific issue in the placeholder above. 


There is also a TAG to add.

2021-07-21 15:11 UTC, sgoggins commented on focus-areas/time-inclusion.md
> +Examples of Global Inclusion which can be implemented include:
"Metrics Candidate Release" is the tag to add to the issue.

2021-07-21 15:19 UTC, merged